/**
 * Generated by scripts/collectibles.mts — do not edit.
 *
 * The artwork and the real collector counts behind every entry in
 * content/collectibles.ts, from POAP's API and Unlock Protocol's.
 *
 * \`imageUrl\` is a path under public/, not the issuer's URL: the originals
 * are full-resolution animated GIFs totalling about 100 MB, and next/image
 * passes animated formats through without optimising them. They are fetched,
 * flattened to their first frame and resized to 160px webp at build time.
 *
 * This exists because POAP retired every public drop page — poap.gallery,
 * drops.poap.xyz and collectors.poap.xyz all redirect to their homepage — so
 * there was nothing left to link to. The page shows the thing instead.
 *
 * \`name\` is what the issuer calls it, which is not always what the registry
 * calls it; the page keeps the registry's name as the heading and this is here
 * so the two can be compared. \`collectors\` is POAP's own count and beats the
 * one the organisers wrote down. Unlock does not publish a holder count, so
 * those stay null and the registry's figure stands.
 *
 * Regenerate with \`npm run collectibles\`; \`npm run build\` does it, and skips
 * on a machine with no POAP_API_KEY.
 */
export interface CollectibleArt {
  name: string;
  imageUrl: string;
  collectors: number | null;
}

/** Keyed by POAP drop id. */
export const POAP_DROPS: Readonly<Record<number, CollectibleArt>> = {
  93758: { name: "Opening Ethereum in Cali", imageUrl: "/collectibles/poap-93758.webp", collectors: 1 },
  147806: { name: "ENCUENTRO DE EMPRESARIOS DEL PACIFICO COLOMBIANO #1", imageUrl: "/collectibles/poap-147806.webp", collectors: 13 },
  147944: { name: "SET-UP EN EVM> Una Wallet, Una Token y un NFT", imageUrl: "/collectibles/poap-147944.webp", collectors: 18 },
  150539: { name: "Ethereum Starter Pack #4 - NFT 101 ICESI", imageUrl: "/collectibles/poap-150539.webp", collectors: 6 },
  157654: { name: "DATADAY EN UAO - Blockchain Analytics", imageUrl: "/collectibles/poap-157654.webp", collectors: 3 },
  159246: { name: "Taller Programación de Contratos Inteligentes con Solidity - ICESI", imageUrl: "/collectibles/poap-159246.webp", collectors: 15 },
  195225: { name: "Destino Devconnect - La Sucursal del Cielo + 10 Years Ethereum", imageUrl: "/collectibles/poap-195225.webp", collectors: 9 },
  197326: { name: "Curso DEFI en USB CALI - Infraestructura de la web3", imageUrl: "/collectibles/poap-197326.webp", collectors: 24 },
  197331: { name: "Curso DEFI USB 2025-2 - Un Mundo Tokenizado", imageUrl: "/collectibles/poap-197331.webp", collectors: 25 },
  198655: { name: "Curso DEFI USB 2025-2 - Clase III Apps y Protocolos DeFi", imageUrl: "/collectibles/poap-198655.webp", collectors: 33 },
  198658: { name: "Curso DEFI USB 2025-2 - Clase IV  TradFi vs Defi + Riesgos y Regulación", imageUrl: "/collectibles/poap-198658.webp", collectors: 13 },
  201984: { name: "Curso DEFI USB 2025-2 - Clase V DAOs y Gobernanza en la era Digital", imageUrl: "/collectibles/poap-201984.webp", collectors: 31 },
  202090: { name: "Curso DEFI USB 2025-2 - Clase VI WEB3 Funding", imageUrl: "/collectibles/poap-202090.webp", collectors: 29 },
  205678: { name: "Curso DEFI USB 2025-2 - Clase VII Mercados con AI", imageUrl: "/collectibles/poap-205678.webp", collectors: 31 },
  205884: { name: "Curso DEFI USB 2025-2 - Clase VIII Prediccion de Mercados", imageUrl: "/collectibles/poap-205884.webp", collectors: 22 },
  209387: { name: "Crea tu app en ethereum", imageUrl: "/collectibles/poap-209387.webp", collectors: 4 },
  211588: { name: "Coworking ETHGlobal x ETHCALI – Cali, 2025", imageUrl: "/collectibles/poap-211588.webp", collectors: 16 },
  218106: { name: "Uniswap Day: Cali", imageUrl: "/collectibles/poap-218106.webp", collectors: 22 },
  224092: { name: "Get ready with ETH CALI for Hack money 2026", imageUrl: "/collectibles/poap-224092.webp", collectors: 15 },
};

/** Keyed by lock address, lowercase. */
export const UNLOCK_LOCKS: Readonly<Record<string, CollectibleArt>> = {
  "0x70bd76e89478400d9ee4c0f1200e53e751610ecf": { name: "Ethereum Starter Pack #4 - DeFi 101", imageUrl: "/collectibles/unlock-0x70bd76e89478400d9ee4c0f1200e53e751610ecf.webp", collectors: null },
  "0xfcf03741a264a00fda35a5814e669968cab95204": { name: "Ethereum Starter Pack #7 - Seguridad WEB3 / ICESI", imageUrl: "/collectibles/unlock-0xfcf03741a264a00fda35a5814e669968cab95204.webp", collectors: null },
  "0x2296e9d389a8c7dc2598d197e9fe43ea12052883": { name: "Taller Programación de Contratos Inteligentes - ICESI", imageUrl: "/collectibles/unlock-0x2296e9d389a8c7dc2598d197e9fe43ea12052883.webp", collectors: null },
  "0xfc78b9ee7348d4184f85ba8a3a0350216ae950b0": { name: "Ticket for Meetup Cali - QF ETHCO 2024 Q1", imageUrl: "/collectibles/unlock-0xfc78b9ee7348d4184f85ba8a3a0350216ae950b0.webp", collectors: null },
  "0x8db8003c692d68dd20722eda6fc4de8708cd5ed6": { name: "Ticket for DRUMCODE Discoteca 1060", imageUrl: "/collectibles/unlock-0x8db8003c692d68dd20722eda6fc4de8708cd5ed6.webp", collectors: null },
  "0x1337722f177e99c8cd490f432a319d8c7a003ea8": { name: "NFT GENERAL EARLY BIRD - DRUMCODE CALI 2024", imageUrl: "/collectibles/unlock-0x1337722f177e99c8cd490f432a319d8c7a003ea8.webp", collectors: null },
  "0x19f7b2834ca07ececefc21202714b3c667588aa9": { name: "BASE COMMUNITY COLOMBIA", imageUrl: "/collectibles/unlock-0x19f7b2834ca07ececefc21202714b3c667588aa9.webp", collectors: null },
  "0x62a2c557092eafe5c24151ed8e52ecaba6ac44a7": { name: "Financiando Public Goods con Giveth", imageUrl: "/collectibles/unlock-0x62a2c557092eafe5c24151ed8e52ecaba6ac44a7.webp", collectors: null },
  "0x7082f47ca600240f41a2fbee26a894d875a63b2f": { name: "CRIPTO XPEDITION USB FULLDAY 2025", imageUrl: "/collectibles/unlock-0x7082f47ca600240f41a2fbee26a894d875a63b2f.webp", collectors: null },
  "0x95cdea5535e8b601a4b588df8f19bb02c618f0e1": { name: "Ticket for Global Pizza Party Cali 🇨🇴", imageUrl: "/collectibles/unlock-0x95cdea5535e8b601a4b588df8f19bb02c618f0e1.webp", collectors: null },
  "0xce984f9e6335198fff193cc0596489dc9e570f3f": { name: "PAPAYOGIN - Limpiando el Rio Cali con Ethereum", imageUrl: "/collectibles/unlock-0xce984f9e6335198fff193cc0596489dc9e570f3f.webp", collectors: null },
  "0x2744a0d99fc319c37d72ae9e98cba1b351bc37d5": { name: "HACKATHON WEB3", imageUrl: "/collectibles/unlock-0x2744a0d99fc319c37d72ae9e98cba1b351bc37d5.webp", collectors: null },
};
