/**
 * Generated by scripts/dune.mts — do not edit.
 *
 * The onchain figures from dune.com/ethcali, read from each query's last saved
 * run. Regenerate with \`npm run dune\`; \`npm run build\` does it for you, and
 * skips silently on a machine with no DUNE_API_KEY.
 *
 * Every figure covers the same population: the wallets in the Dune dataset
 * \`dataset_users_onboarded_eth_cali\`. They do not all cover the same tables,
 * so they are never presented as adding up:
 *
 * - \`transactions\` and \`chains[].txCount\` come from \`gas.fees\` — one row per
 *   transaction, every chain Dune indexes.
 * - \`volumeUsd\` comes from \`tokens.transfers\`, which counts token movement
 *   and not the transactions that carried it.
 * - \`feesUsd\` and the per-chain fees are a separate run from the totals and
 *   differ from their sum by a few dollars.
 */
export interface DuneChain {
  /** As Dune names it — 'avalanche_c', 'zkevm'. content/site.ts maps these for display. */
  name: string;
  txCount: number;
  /** 0 where the dashboard's fee query filtered the chain out for being under $5. */
  feesUsd: number;
}

export const DUNE = {
  /** The day this file was written, not the day the queries ran. */
  fetchedOn: '2026-09-22',
  usersOnboarded: 441,
  transactions: 484037,
  volumeUsd: 21749900.068047974,
  feesUsd: 38888.39401617681,
  chains: [
    { name: "base", txCount: 138359, feesUsd: 3790.4694493808934 },
    { name: "optimism", txCount: 81030, feesUsd: 2255.0538245849425 },
    { name: "polygon", txCount: 56088, feesUsd: 561.7636048935399 },
    { name: "zora", txCount: 43890, feesUsd: 427.1518122562174 },
    { name: "bnb", txCount: 20797, feesUsd: 4356.0292750627505 },
    { name: "arbitrum", txCount: 18400, feesUsd: 1589.5040482932034 },
    { name: "opbnb", txCount: 16057, feesUsd: 25.17716971063714 },
    { name: "ethereum", txCount: 14185, feesUsd: 19886.140450518968 },
    { name: "linea", txCount: 12555, feesUsd: 1280.4624377702671 },
    { name: "zksync", txCount: 12445, feesUsd: 1220.5402007460748 },
    { name: "scroll", txCount: 7611, feesUsd: 1675.7551141968174 },
    { name: "taiko", txCount: 6089, feesUsd: 127.34658157273034 },
    { name: "blast", txCount: 5773, feesUsd: 439.98230230552065 },
    { name: "avalanche_c", txCount: 5406, feesUsd: 561.2103646186421 },
    { name: "ink", txCount: 5127, feesUsd: 27.972727241982614 },
    { name: "celo", txCount: 5037, feesUsd: 0 },
    { name: "mantle", txCount: 4800, feesUsd: 166.30597958057098 },
    { name: "unichain", txCount: 3994, feesUsd: 7.9131859319085365 },
    { name: "robinhood", txCount: 2814, feesUsd: 47.86080587549261 },
    { name: "berachain", txCount: 2026, feesUsd: 0 },
    { name: "hyperevm", txCount: 1953, feesUsd: 23.72464630202236 },
    { name: "apechain", txCount: 1934, feesUsd: 8.69595513753044 },
    { name: "plume", txCount: 1754, feesUsd: 24.389409336875254 },
    { name: "zkevm", txCount: 1610, feesUsd: 215.33900020228066 },
    { name: "abstract", txCount: 1427, feesUsd: 45.160358873519336 },
    { name: "monad", txCount: 1095, feesUsd: 0 },
    { name: "somnia", txCount: 977, feesUsd: 0 },
    { name: "sonic", txCount: 904, feesUsd: 0 },
    { name: "gnosis", txCount: 768, feesUsd: 0 },
    { name: "worldchain", txCount: 728, feesUsd: 0 },
    { name: "fantom", txCount: 718, feesUsd: 9.47903092374747 },
    { name: "superseed", txCount: 668, feesUsd: 0 },
    { name: "nova", txCount: 632, feesUsd: 0 },
    { name: "katana", txCount: 593, feesUsd: 0 },
    { name: "bob", txCount: 569, feesUsd: 17.165235488238803 },
    { name: "kaia", txCount: 556, feesUsd: 0 },
    { name: "morph", txCount: 463, feesUsd: 12.098607284398607 },
    { name: "ronin", txCount: 454, feesUsd: 0 },
    { name: "sei", txCount: 420, feesUsd: 0 },
    { name: "xlayer", txCount: 394, feesUsd: 13.511633841505919 },
    { name: "boba", txCount: 367, feesUsd: 16.314145448679852 },
    { name: "degen", txCount: 319, feesUsd: 0 },
    { name: "megaeth", txCount: 294, feesUsd: 0 },
    { name: "flare", txCount: 284, feesUsd: 0 },
    { name: "plasma", txCount: 278, feesUsd: 0 },
    { name: "tezos_evm", txCount: 223, feesUsd: 0 },
    { name: "cronos", txCount: 166, feesUsd: 23.263586132426557 },
    { name: "lens", txCount: 162, feesUsd: 0 },
    { name: "shape", txCount: 155, feesUsd: 0 },
    { name: "arc", txCount: 141, feesUsd: 0 },
    { name: "story", txCount: 126, feesUsd: 0 },
    { name: "flow", txCount: 80, feesUsd: 0 },
    { name: "sophon", txCount: 80, feesUsd: 0 },
    { name: "hemi", txCount: 73, feesUsd: 0 },
    { name: "b3", txCount: 65, feesUsd: 0 },
    { name: "mezo", txCount: 39, feesUsd: 0 },
    { name: "peaq", txCount: 33, feesUsd: 0 },
    { name: "corn", txCount: 30, feesUsd: 0 },
    { name: "tac", txCount: 22, feesUsd: 0 },
  ] as readonly DuneChain[],
} as const;
