/**
 * Generated by scripts/dune.mts — do not edit.
 *
 * The onchain figures from dune.com/ethcali, read from each query's last saved
 * run. Regenerate with \`npm run dune\`; \`npm run build\` does it for you, and
 * skips silently on a machine with no DUNE_API_KEY.
 *
 * Every figure covers the same population: the wallets in the Dune dataset
 * \`dataset_users_onboarded_eth_cali\`. They do not all cover the same tables,
 * so they are never presented as adding up:
 *
 * - \`transactions\` and \`chains[].txCount\` come from \`gas.fees\` — one row per
 *   transaction, every chain Dune indexes.
 * - \`volumeUsd\` and \`chains[].volumeUsd\` come from \`tokens.transfers\`,
 *   which counts token movement and not the transactions that carried it. The
 *   total is the exact sum of the per-chain rows: one query, one run.
 * - \`feesUsd\` and the per-chain fees are a separate run from the totals and
 *   differ from their sum by a few dollars.
 */
export interface DuneChain {
  /** As Dune names it — 'avalanche_c', 'zkevm'. content/site.ts maps these for display. */
  name: string;
  txCount: number;
  volumeUsd: number;
  /** 0 where the dashboard's fee query filtered the chain out for being under $5. */
  feesUsd: number;
}

export const DUNE = {
  /** The day this file was written, not the day the queries ran. */
  fetchedOn: '2026-09-22',
  usersOnboarded: 441,
  transactions: 484037,
  volumeUsd: 21749900.068048,
  feesUsd: 38888.39401617681,
  chains: [
    { name: "ethereum", txCount: 14185, volumeUsd: 11861504.715635004, feesUsd: 19886.140450518968 },
    { name: "polygon", txCount: 56088, volumeUsd: 2598737.215696507, feesUsd: 561.7636048935399 },
    { name: "base", txCount: 138359, volumeUsd: 2012156.2927636523, feesUsd: 3790.4694493808934 },
    { name: "optimism", txCount: 81030, volumeUsd: 1585972.679854726, feesUsd: 2255.0538245849425 },
    { name: "arbitrum", txCount: 18400, volumeUsd: 1342408.9960128746, feesUsd: 1589.5040482932034 },
    { name: "zksync", txCount: 12445, volumeUsd: 641193.5481270329, feesUsd: 1220.5402007460748 },
    { name: "bnb", txCount: 20797, volumeUsd: 547423.6480334074, feesUsd: 4356.0292750627505 },
    { name: "avalanche_c", txCount: 5406, volumeUsd: 262983.52672584367, feesUsd: 561.2103646186421 },
    { name: "scroll", txCount: 7611, volumeUsd: 190394.2436224969, feesUsd: 1675.7551141968174 },
    { name: "linea", txCount: 12555, volumeUsd: 170442.1519714728, feesUsd: 1280.4624377702671 },
    { name: "celo", txCount: 5037, volumeUsd: 152838.41477207423, feesUsd: 0 },
    { name: "blast", txCount: 5773, volumeUsd: 67627.81549335778, feesUsd: 439.98230230552065 },
    { name: "mantle", txCount: 4800, volumeUsd: 48439.126615727015, feesUsd: 166.30597958057098 },
    { name: "zora", txCount: 43890, volumeUsd: 47240.79287898072, feesUsd: 427.1518122562174 },
    { name: "zkevm", txCount: 1610, volumeUsd: 42280.27088578416, feesUsd: 215.33900020228066 },
    { name: "unichain", txCount: 3994, volumeUsd: 32284.146930659866, feesUsd: 7.9131859319085365 },
    { name: "abstract", txCount: 1427, volumeUsd: 26608.486302288915, feesUsd: 45.160358873519336 },
    { name: "taiko", txCount: 6089, volumeUsd: 23378.315424231027, feesUsd: 127.34658157273034 },
    { name: "hyperevm", txCount: 1953, volumeUsd: 16559.65794585504, feesUsd: 23.72464630202236 },
    { name: "gnosis", txCount: 768, volumeUsd: 15321.947957453936, feesUsd: 0 },
    { name: "ink", txCount: 5127, volumeUsd: 14121.108561740553, feesUsd: 27.972727241982614 },
    { name: "opbnb", txCount: 16057, volumeUsd: 13311.037189403844, feesUsd: 25.17716971063714 },
    { name: "berachain", txCount: 2026, volumeUsd: 11691.184013955259, feesUsd: 0 },
    { name: "fantom", txCount: 718, volumeUsd: 3434.247168710219, feesUsd: 9.47903092374747 },
    { name: "apechain", txCount: 1934, volumeUsd: 3393.9555582121698, feesUsd: 8.69595513753044 },
    { name: "monad", txCount: 1095, volumeUsd: 3179.9918192943137, feesUsd: 0 },
    { name: "plume", txCount: 1754, volumeUsd: 2369.691694086782, feesUsd: 24.389409336875254 },
    { name: "degen", txCount: 319, volumeUsd: 2296.55322926888, feesUsd: 0 },
    { name: "worldchain", txCount: 728, volumeUsd: 1885.6761709575467, feesUsd: 0 },
    { name: "sonic", txCount: 904, volumeUsd: 1337.1976590669829, feesUsd: 0 },
    { name: "somnia", txCount: 977, volumeUsd: 1267.1104406791906, feesUsd: 0 },
    { name: "morph", txCount: 463, volumeUsd: 1183.9218245179475, feesUsd: 12.098607284398607 },
    { name: "xlayer", txCount: 394, volumeUsd: 970.1126495399487, feesUsd: 13.511633841505919 },
    { name: "plasma", txCount: 278, volumeUsd: 674.9523618049967, feesUsd: 0 },
    { name: "katana", txCount: 593, volumeUsd: 533.1698972745534, feesUsd: 0 },
    { name: "ronin", txCount: 454, volumeUsd: 518.5442060169736, feesUsd: 0 },
    { name: "robinhood", txCount: 2814, volumeUsd: 503.6876905649335, feesUsd: 47.86080587549261 },
    { name: "cronos", txCount: 166, volumeUsd: 345.4707237762961, feesUsd: 23.263586132426557 },
    { name: "story", txCount: 126, volumeUsd: 197.30106103713086, feesUsd: 0 },
    { name: "superseed", txCount: 668, volumeUsd: 187.6221972114465, feesUsd: 0 },
    { name: "lens", txCount: 162, volumeUsd: 148.95845573834794, feesUsd: 0 },
    { name: "bob", txCount: 569, volumeUsd: 110.79296990304593, feesUsd: 17.165235488238803 },
    { name: "flare", txCount: 284, volumeUsd: 82.59763591801115, feesUsd: 0 },
    { name: "mezo", txCount: 39, volumeUsd: 81.49121525698334, feesUsd: 0 },
    { name: "hemi", txCount: 73, volumeUsd: 65.7642928081875, feesUsd: 0 },
    { name: "sei", txCount: 420, volumeUsd: 49.32565800753838, feesUsd: 0 },
    { name: "megaeth", txCount: 294, volumeUsd: 38.78756418948581, feesUsd: 0 },
    { name: "nova", txCount: 632, volumeUsd: 37.892646330352925, feesUsd: 0 },
    { name: "b3", txCount: 65, volumeUsd: 18.914010176749727, feesUsd: 0 },
    { name: "shape", txCount: 155, volumeUsd: 18.711703077199022, feesUsd: 0 },
    { name: "arc", txCount: 141, volumeUsd: 17.578420865000002, feesUsd: 0 },
    { name: "sophon", txCount: 80, volumeUsd: 14.170455735880331, feesUsd: 0 },
    { name: "boba", txCount: 367, volumeUsd: 11.774692279431543, feesUsd: 16.314145448679852 },
    { name: "peaq", txCount: 33, volumeUsd: 2.4592642986666666, feesUsd: 0 },
    { name: "kaia", txCount: 556, volumeUsd: 0.862133278330105, feesUsd: 0 },
    { name: "corn", txCount: 30, volumeUsd: 0.26203783699117006, feesUsd: 0 },
    { name: "tezos_evm", txCount: 223, volumeUsd: 0, feesUsd: 0 },
    { name: "flow", txCount: 80, volumeUsd: 0, feesUsd: 0 },
    { name: "tac", txCount: 22, volumeUsd: 0, feesUsd: 0 },
  ] as readonly DuneChain[],
} as const;
