/**
 * Generated by scripts/hackathon-nav.mts — do not edit.
 *
 * The published hackathons and hacker houses, newest first, for the nav menu.
 * Regenerate with `npm run nav`; `npm run build` does it for you.
 *
 * `name.en` falls back to the Spanish name, the same rule `localized()`
 * applies everywhere else: a half-translated event reads as Spanish, never as a
 * blank menu entry.
 */
export interface NavHackathon {
  slug: string;
  kind: 'hackathon' | 'hacker_house';
  startsOn: string;
  name: { es: string; en: string };
}

export const NAV_HACKATHONS: readonly NavHackathon[] = [
  { slug: "ethereum-builders-tour-cali", kind: "hackathon", startsOn: "2026-09-19", name: { es: "Ethereum Builders Tour: Cali", en: "Ethereum Builders Tour: Cali" } },
  { slug: "hackathon-web3-cali", kind: "hackathon", startsOn: "2025-06-13", name: { es: "Hackathon WEB3 Cali", en: "Hackathon WEB3 Cali" } },
  { slug: "hacksession-base-batch-latam-zonamerica-colombia", kind: "hackathon", startsOn: "2025-05-09", name: { es: "Hacksession Base Batch LATAM: Zonamerica Colombia", en: "Hacksession Base Batch LATAM: Zonamerica Colombia" } },
  { slug: "hackathon-web3-ethcolombia", kind: "hackathon", startsOn: "2023-11-27", name: { es: "Hackathon WEB3 Ethcolombia", en: "Hackathon WEB3 Ethcolombia" } },
];
