/**
 * Writes the hackathon list the nav menu renders.
 *
 * The menu has to name every hackathon, and the nav is a static array rendered
 * by `Layout` on every page — which has no data and no place to fetch any. The
 * list is therefore resolved at build time into a committed module.
 *
 * Committed, not gitignored like the brand kit. If Supabase is unreachable
 * during a build this script keeps whatever is already on disk and warns rather
 * than emptying the menu, and that is only safe if the file is in git to begin
 * with. A build that silently drops every hackathon from the nav is worse than
 * one that ships a menu a day out of date.
 *
 * The cost is honest and worth stating: adding a hackathon in the CMS shows up
 * on `/hackathons` within a minute through ISR, and in this menu on the next
 * deploy. `/hackathons` is the authority; this is a shortcut to it.
 *
 * Run: npm run nav
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { createClient } from '@supabase/supabase-js';

const ROOT = resolve(import.meta.dirname, '..');
const OUT = join(ROOT, 'content/hackathons.generated.ts');

/** `.env.local` is not loaded for a bare tsx run the way `next` loads it. */
function env(key: string): string | undefined {
  if (process.env[key]) return process.env[key];
  try {
    const line = readFileSync(join(ROOT, '.env.local'), 'utf8')
      .split('\n')
      .find((l) => l.startsWith(`${key}=`));
    return line?.slice(key.length + 1).trim() || undefined;
  } catch {
    return undefined;
  }
}

const url = env('NEXT_PUBLIC_SUPABASE_URL');
const key = env('NEXT_PUBLIC_SUPABASE_ANON_KEY');

function keepExisting(why: string): never {
  // Exit 0 deliberately: a missing key on a contributor's machine, or a blip
  // from Supabase, should not stop them building the site.
  console.warn(`nav: ${why} — keeping the committed hackathon list.`);
  process.exit(0);
}

if (!url || !key) keepExisting('no Supabase credentials');

const supabase = createClient(url!, key!);
const { data, error } = await supabase
  .from('events')
  .select('slug, kind, name_es, name_en, starts_on')
  .in('kind', ['hackathon', 'hacker_house'])
  .order('starts_on', { ascending: false });

if (error) keepExisting(`Supabase said "${error.message}"`);
if (!data?.length) keepExisting('Supabase returned no hackathons');

const rows = data!
  .map(
    (e) =>
      `  { slug: ${JSON.stringify(e.slug)}, kind: ${JSON.stringify(e.kind)}, ` +
      `startsOn: ${JSON.stringify(e.starts_on)}, ` +
      `name: { es: ${JSON.stringify(e.name_es)}, en: ${JSON.stringify(e.name_en ?? e.name_es)} } },`
  )
  .join('\n');

writeFileSync(
  OUT,
  `/**
 * Generated by scripts/hackathon-nav.mts — do not edit.
 *
 * The published hackathons and hacker houses, newest first, for the nav menu.
 * Regenerate with \`npm run nav\`; \`npm run build\` does it for you.
 *
 * \`name.en\` falls back to the Spanish name, the same rule \`localized()\`
 * applies everywhere else: a half-translated event reads as Spanish, never as a
 * blank menu entry.
 */
export interface NavHackathon {
  slug: string;
  kind: 'hackathon' | 'hacker_house';
  startsOn: string;
  name: { es: string; en: string };
}

export const NAV_HACKATHONS: readonly NavHackathon[] = [
${rows}
];
`,
  'utf8'
);

console.log(`nav: ${data!.length} hackathons -> content/hackathons.generated.ts`);
